import { Light as SyntaxHighlighter } from "react-syntax-highlighter";

import js from "react-syntax-highlighter/dist/cjs/languages/hljs/java";
import java from "react-syntax-highlighter/dist/cjs/languages/hljs/java";
import cpp from "react-syntax-highlighter/dist/cjs/languages/hljs/cpp";
import clang from "react-syntax-highlighter/dist/cjs/languages/hljs/c";
import json from "react-syntax-highlighter/dist/cjs/languages/hljs/json";
import rust from "react-syntax-highlighter/dist/cjs/languages/hljs/rust";
import ts from "react-syntax-highlighter/dist/cjs/languages/hljs/typescript";
import css from "react-syntax-highlighter/dist/cjs/languages/hljs/css";
import xml from "react-syntax-highlighter/dist/cjs/languages/hljs/xml";
import asm from "react-syntax-highlighter/dist/cjs/languages/hljs/x86asm";
import shell from "react-syntax-highlighter/dist/cjs/languages/hljs/shell";
import powershell from "react-syntax-highlighter/dist/cjs/languages/hljs/powershell";
import python from "react-syntax-highlighter/dist/cjs/languages/hljs/python";
import groovy from "react-syntax-highlighter/dist/cjs/languages/hljs/groovy";
SyntaxHighlighter.registerLanguage("javascript", js);
SyntaxHighlighter.registerLanguage("java", java);
SyntaxHighlighter.registerLanguage("cpp", cpp);
SyntaxHighlighter.registerLanguage("c", clang);
SyntaxHighlighter.registerLanguage("json", json);
SyntaxHighlighter.registerLanguage("rust", rust);
SyntaxHighlighter.registerLanguage("typescript", ts);
SyntaxHighlighter.registerLanguage("css", css);
SyntaxHighlighter.registerLanguage("xml", xml);
SyntaxHighlighter.registerLanguage("asm", asm);
SyntaxHighlighter.registerLanguage("shell", shell);
SyntaxHighlighter.registerLanguage("powershell", powershell);
SyntaxHighlighter.registerLanguage("python", python);
SyntaxHighlighter.registerLanguage("groovy", groovy);

export { SyntaxHighlighter };
