/**
 * Regenerate the site's SVG logo outlines from Inconsolata at weight 600.
 *
 * The checked-in TTF was decoded from @fontsource-variable/inconsolata 5.2.8.
 * It stays in scripts/assets and is covered by
 * src/features/site/Inconsolata-OFL.txt.
 *
 * Run `pnpm logo:generate` to rewrite the paths, or
 * `pnpm logo:generate --check` to verify the committed output.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as fontkit from "fontkit";
import type { PathCommand } from "fontkit";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const fontPath = resolve(root, "scripts/assets/inconsolata-latin-wght-normal.ttf");
const outputPath = resolve(root, "src/features/site/logo-glyphs.ts");
const characters = "012SITU";
const scale = 0.016; // 16px / 1000 font units
const baseline = 13.35;

function format(value: number): string {
  return Number(value.toFixed(3)).toString();
}

function point(args: number[], index: number): string {
  const x = args[index];
  const y = args[index + 1];
  if (x === undefined || y === undefined) throw new Error("Invalid glyph path point");
  return `${format(4 + x * scale)} ${format(baseline - y * scale)}`;
}

function svgPath(commands: PathCommand[]): string {
  return commands.map(({ command, args }) => {
    switch (command) {
      case "moveTo":
        return `M${point(args, 0)}`;
      case "lineTo":
        return `L${point(args, 0)}`;
      case "quadraticCurveTo":
        return `Q${point(args, 0)} ${point(args, 2)}`;
      case "bezierCurveTo":
        return `C${point(args, 0)} ${point(args, 2)} ${point(args, 4)}`;
      case "closePath":
        return "Z";
      default:
        throw new Error(`Unknown glyph path command: ${command}`);
    }
  }).join("");
}

function generate(): string {
  const loaded = fontkit.openSync(fontPath);
  if (!("getVariation" in loaded)) throw new Error("Expected a single font");
  if (loaded.unitsPerEm !== 1000) throw new Error("Expected a 1000-unit em square");
  if (!loaded.variationAxes.wght) throw new Error("Expected a weight axis");
  const font = loaded.getVariation({ wght: 600 });

  const lines = [
    "// Generated by scripts/generate-logo-glyphs.ts from Inconsolata at weight 600.",
    "// Source: @fontsource-variable/inconsolata (SIL Open Font License 1.1).",
    "export const logoGlyphPaths = {",
  ];
  for (const char of characters) {
    const glyph = font.glyphForCodePoint(char.charCodeAt(0));
    if (glyph.advanceWidth !== 500) throw new Error(`Expected a 500-unit advance for ${char}`);
    lines.push(`  '${char}': '${svgPath(glyph.path.commands)}',`);
  }
  lines.push("} as const;");
  return `${lines.join("\n")}\n`;
}

const args = process.argv.slice(2);
if (args.some(arg => arg !== "--check")) throw new Error(`Unknown argument: ${args.join(" ")}`);
const generated = generate();
if (args.includes("--check")) {
  if (readFileSync(outputPath, "utf8") !== generated) {
    throw new Error(`Outdated SVG paths: ${outputPath}. Run pnpm logo:generate.`);
  }
  console.log(`Up to date: ${outputPath}`);
} else {
  writeFileSync(outputPath, generated);
  console.log(`Wrote: ${outputPath}`);
}
